export const INGREDIENT_ADDER = 'INGREDIENT_ADDER';
export const INGREDIENT_REMOVER = 'INGREDIENT_REMOVER';
export const FETCHED_INGREDIENTS = 'FETCHED_INGREDIENTS';
export const INGREDIENTS_ERROR = 'INGREDIENTS_ERROR';

export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAILURE = 'ORDER_FAILURE';
export const ON_ORDERSTART = 'ON_ORDERSTART';
export const ORDER_INIT = 'ORDER_INIT';


export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_FAILURE = 'ORDERS_FAILURE';
export const ORDERS_START = 'ORDERS_START';

export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";


export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';


export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const ONAUTHCHANGE_REQUEST = 'ONAUTHCHANGE_REQUEST';
export const ONAUTHCHANGE_SUCCESS = 'ONAUTHCHANGE_SUCCESS';
export const ONAUTHCHANGE_FAILURE = 'ONAUTHCHANGE_FAILURE';

export const ON_PATHCHANGE = "ON_PATHCHANGE";


// export const VERIFY_REQUEST = "VERIFY_REQUEST";
// export const VERIFY_SUCCESS = "VERIFY_SUCCESS";





