export const INGREDIENT_ADDER = 'INGREDIENT_ADDER';
export const INGREDIENT_REMOVER = 'INGREDIENT_REMOVER';
export const FETCHED_INGREDIENTS = 'FETCHED_INGREDIENTS';
export const INGREDIENTS_ERROR = 'INGREDIENTS_ERROR';

export const ORDER_SUCCESS = 'ORDER_SUCCESS';
export const ORDER_FAILURE = 'ORDER_FAILURE';
export const ON_ORDERSTART = 'ON_ORDERSTART';
export const ORDER_INIT = 'ORDER_INIT';


export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
export const ORDERS_FAILURE = 'ORDERS_FAILURE';
export const ORDERS_START = 'ORDERS_START';


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';





